# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-19 21:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('user', models.ManyToManyField(blank=True, related_name='creators', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
