# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-20 18:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('creators', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='as_creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
