# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-22 17:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0013_entry_help_types'),
        ('creators', '0002_creator_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderedCreatorRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries_by', to='creators.Creator')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to='entries.Entry')),
            ],
            options={
                'verbose_name': 'Ordered creator record',
            },
        ),
    ]
