# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-19 21:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0011_remove_entry_is_approved'),
        ('creators', '0002_creator_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderedEntryCreator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creators.Creator')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='entries.Entry')),
            ],
        ),
    ]
