# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-24 17:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0003_orderedcreatorrecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderedcreatorrecord',
            options={'ordering': ['pk'], 'verbose_name': 'Ordered creator record'},
        ),
    ]
