# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-24 20:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0004_auto_20170824_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedcreatorrecord',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_entries', to='creators.Creator'),
        ),
        migrations.AlterField(
            model_name='orderedcreatorrecord',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_creators', to='entries.Entry'),
        ),
    ]
