# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-04 16:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('creators', '0005_auto_20170824_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_creator', to='profiles.UserProfile'),
        ),
    ]
