# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-04 16:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0007_auto_20171004_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creator',
            name='user',
        ),
    ]
