# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-25 19:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0010_auto_20171012_2002'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creator',
            options={'ordering': ['name'], 'verbose_name': 'Creator'},
        ),
    ]
