# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-18 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0012_auto_20180318_1808'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='entrycreator',
            index=models.Index(fields=['entry', '_order'], name='creators_en_entry_i_b199e7_idx'),
        ),
    ]
