# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-10 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0022_auto_20180326_2211'),
        ('profiles', '0017_auto_20180213_1202'),
        ('creators', '0012_auto_20180318_1808'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='entrycreator',
            unique_together=set([('entry', 'profile')]),
        ),
        migrations.AddIndex(
            model_name='entrycreator',
            index=models.Index(fields=['entry', '_order'], name='creators_en_entry_i_b199e7_idx'),
        ),
        migrations.AddIndex(
            model_name='entrycreator',
            index=models.Index(fields=['entry', 'profile'], name='creators_en_entry_i_968f03_idx'),
        ),
    ]
