# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-16 22:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0013_auto_20180410_2055'),
        ('profiles', '0018_replace_creators_with_entrycreators')
    ]

    operations = [
        migrations.RemoveField(
            model_name='creator',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='orderedcreatorrecord',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='orderedcreatorrecord',
            name='entry',
        ),
        migrations.DeleteModel(
            name='Creator',
        ),
        migrations.DeleteModel(
            name='OrderedCreatorRecord',
        ),
    ]
