# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-17 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0014_auto_20180416_2252'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='entrycreator',
            name='creators_en_entry_i_b199e7_idx',
        ),
        migrations.RemoveIndex(
            model_name='entrycreator',
            name='creators_en_entry_i_968f03_idx',
        ),
        migrations.AddIndex(
            model_name='entrycreator',
            index=models.Index(fields=['entry', '_order'], name='uk_entrycreator_entryid_order'),
        ),
        migrations.AddIndex(
            model_name='entrycreator',
            index=models.Index(fields=['entry', 'profile'], name='uk_entrycreator_entry_profile'),
        ),
    ]
