# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-20 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('creators', '0001_initial'),
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('description', models.CharField(blank=True, max_length=600)),
                ('content_url', models.URLField()),
                ('thumbnail_url', models.URLField(blank=True)),
                ('get_involved', models.CharField(blank=True, max_length=300)),
                ('get_involved_url', models.URLField(blank=True)),
                ('interest', models.CharField(blank=True, max_length=600)),
                ('featured', models.BooleanField()),
                ('internal_notes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('creators', models.ManyToManyField(blank=True, related_name='entries', to='creators.Creator')),
                ('issues', models.ManyToManyField(blank=True, related_name='entries', to='issues.Issue')),
            ],
            options={
                'verbose_name_plural': 'entries',
            },
        ),
    ]
