# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-20 20:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('issues', '0001_initial'),
        ('creators', '0002_auto_20161219_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('description', models.CharField(max_length=300)),
                ('content_url', models.URLField()),
                ('thumbnail_url', models.URLField()),
                ('get_involved', models.CharField(max_length=300)),
                ('get_involved_url', models.URLField()),
                ('interest', models.CharField(max_length=300)),
                ('featured', models.BooleanField()),
                ('internal_notes', models.TextField()),
                ('creators', models.ManyToManyField(blank=True, related_name='entries', to='creators.Creator')),
                ('issues', models.ManyToManyField(blank=True, related_name='entries', to='issues.Issue')),
                ('published_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='entries', to='tags.Tag')),
            ],
            options={
                'verbose_name_plural': 'entries',
            },
        ),
    ]
