# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-20 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_auto_20170123_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
