# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-01 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0004_entry_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='is_approved',
            field=models.BooleanField(default=True, help_text='Should this show up on the site?'),
        ),
    ]
