# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-25 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0005_entry_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Should this show up on the site?'),
        ),
    ]
