# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-25 22:39
from __future__ import unicode_literals

from django.db import migrations, models
from pulseapi.entries.models import ModerationState

def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    # issue = apps.get_model("issues", "Issue")
    db_alias = schema_editor.connection.alias
    ModerationState.objects.using(db_alias).bulk_create([
        ModerationState(name="Pending"),
        ModerationState(name="In Review"),
        ModerationState(name="Approved"),
        ModerationState(name="Declined"),
    ])

class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0006_auto_20170525_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RunPython(forwards_func),
    ]
