# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-25 22:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
from pulseapi.entries.models import ModerationState, Entry, get_default_moderation_state


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    # issue = apps.get_model("issues", "Issue")
    db_alias = schema_editor.connection.alias
    approved = ModerationState.objects.using(db_alias).get(name='Approved')
    entries = Entry.objects.using(db_alias).all()
    for entry in entries:
        if entry.is_approved:
            entry.moderation_state = approved
            entry.save()


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0007_moderationstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='moderation_state',
            field=models.ForeignKey(default=get_default_moderation_state, on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='entries.ModerationState'),
        ),
        migrations.RunPython(forwards_func),
    ]
