# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-25 22:39
from __future__ import unicode_literals

from django.db import migrations, models
from pulseapi.entries.models import ModerationState

def forwards_func(apps, schema_editor):
    # Set up four common moderation states if they don't exist yet
    ModerationState.objects.get_or_create(name="Pending")
    ModerationState.objects.get_or_create(name="In Review")
    ModerationState.objects.get_or_create(name="Approved")
    ModerationState.objects.get_or_create(name="Declined")

class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0007_moderationstate'),
    ]

    operations = [
        migrations.RunPython(forwards_func),
    ]
