# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-25 22:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
from pulseapi.entries.models import get_default_moderation_state


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0008_moderationstate_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='moderation_state',
            field=models.ForeignKey(default=get_default_moderation_state, on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='entries.ModerationState'),
        ),
    ]
