# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-25 23:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0010_migrate_approval_flags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='is_approved',
        ),
    ]
