# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-29 19:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0011_remove_entry_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='thumbnail_url',
        ),
    ]
