# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-19 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0003_orderedentrycreator'),
        ('entries', '0011_remove_entry_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='ordered_creators',
            field=models.ManyToManyField(blank=True, through='creators.OrderedEntryCreator', to='creators.Creator'),
        ),
    ]
