# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-19 21:46
from __future__ import unicode_literals

from django.db import migrations, models
from pulseapi.entries.models import Entry
from pulseapi.creators.models import OrderedEntryCreator

def forwards_func(apps, schema_editor):
    """
    Migrate Entry.creators to Entry.ordered_creators,
    because Django can't do this on its own.
    """
    entries = Entry.objects.all();
    for entry in entries:
        for creator in entry.creators:
            entry.ordered_creators.add(
                OrderedEntryCreator(
                    entry=entry,
                    creator=creator
                )
            )
        entry.save()


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0012_entry_ordered_creators'),
    ]

    operations = [
        migrations.RunPython(forwards_func),
    ]
