# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-19 21:46
from __future__ import unicode_literals

from django.db import migrations, models
from pulseapi.entries.models import Entry
from pulseapi.creators.models import Creator, OrderedEntryCreator

def forwards_func(apps, schema_editor):
    """
    Migrate Entry.creators to Entry.ordered_creators,
    because Django can't do this on its own. Note
    that original ordering has already been lost,
    so we are not concerned with "Getting the order right"
    while performing this migration.
    """
    DBEntry = apps.get_model('entries', 'Entry')
    entries = DBEntry.objects.all();

    for entry in entries:
        for cid, creator in enumerate(entry.creators.all()):
            refentry = Entry.objects.get(id=entry.id)
            refcreator = Creator.objects.get(id=creator.id)
            OrderedEntryCreator.objects.get_or_create(
                entry=refentry,
                creator=refcreator,
                order=cid
            )


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0012_entry_ordered_creators'),
    ]

    operations = [
        migrations.RunPython(forwards_func),
    ]
