# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-19 22:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0013_copy_creators_to_ordered_creators'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='creators',
        ),
    ]
