# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-22 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0003_orderedcreatorrecord'),
        ('entries', '0013_entry_help_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='orderedcreators',
            field=models.ManyToManyField(through='creators.OrderedCreatorRecord', to='creators.Creator'),
        ),
    ]
