# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-19 22:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0014_remove_entry_creators'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='ordered_creators',
            new_name='creators',
        ),
    ]
