# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-22 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0015_copy_creators_to_ordered_creators'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='creators',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='orderedcreators',
            new_name='creators',
        ),
    ]
