# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-24 17:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0016_auto_20170822_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='creators',
        ),
    ]
