# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-24 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0004_auto_20170824_1049'),
        ('entries', '0017_remove_entry_creators'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='creators',
            field=models.ManyToManyField(through='creators.OrderedCreatorRecord', to='creators.Creator'),
        ),
    ]
