# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-03 16:32
from __future__ import unicode_literals

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0019_remove_entry_creators'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='published_by_creator',
            field=models.BooleanField(default=False),
        ),
    ]
