# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-06 10:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0020_entry_published_by_creator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['id'], 'verbose_name_plural': 'entries'},
        ),
    ]
