# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-26 22:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0021_auto_20180306_1045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-id'], 'verbose_name_plural': 'entries'},
        ),
    ]
