# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-23 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0023_auto_20180430_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='entry_type',
            field=models.CharField(choices=[('base', 'base'), ('project', 'project'), ('news', 'news'), ('curriculum', 'curriculum'), ('research', 'research'), ('session', 'session')], default='base', max_length=20),
        ),
    ]
