# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-11 18:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pulseapi.profiles.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entries', '0013_entry_help_types'),
        ('issues', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=500, null=True)),
                ('country', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('service', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserBookmarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_by', to='entries.Entry')),
            ],
            options={
                'verbose_name': 'Bookmarks',
                'verbose_name_plural': 'Bookmarks',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_bio', models.CharField(blank=True, default='', max_length=140)),
                ('custom_name', models.CharField(blank=True, max_length=500, null=True)),
                ('is_group', models.BooleanField(default=False)),
                ('thumbnail', models.ImageField(blank=True, max_length=2048, upload_to=pulseapi.profiles.models.entry_thumbnail_path)),
                ('bookmarks', models.ManyToManyField(through='profiles.UserBookmarks', to='entries.Entry')),
                ('issues', models.ManyToManyField(to='issues.Issue')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
            },
        ),
        migrations.AddField(
            model_name='userbookmarks',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks_from', to='profiles.UserProfile'),
        ),
        migrations.AddField(
            model_name='socialurl',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.UserProfile'),
        ),
        migrations.AddField(
            model_name='location',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.UserProfile'),
        ),
    ]
