# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-03 20:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

from pulseapi.users.models import EmailUser
from pulseapi.profiles.models import UserProfile

def ensure_user_profiles(app, schema_editor):
    for user in EmailUser.objects.all():
        (profile,created) = UserProfile.objects.get_or_create(user=user)

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(ensure_user_profiles),
    ]
