# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-04 18:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_userbookmarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbookmarks',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookmark_entries_from_profile', to='profiles.UserProfile'),
        ),
    ]
