# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-04 19:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_copy_user_bookmarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbookmarks',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmark_entries_from_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
