# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-11 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20170810_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='location',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.ManyToManyField(related_name='Profile', to='profiles.Location'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='social_urls',
            field=models.ManyToManyField(related_name='Profile', to='profiles.SocialUrl'),
        ),
    ]
