# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-12 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20170907_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='custom_name',
            field=models.CharField(blank=True, max_length=70),
        ),
    ]
