# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-01-30 17:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_remove_userprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='affiliation',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='enable_extended_information',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_bio_long',
            field=models.CharField(blank=True, max_length=4096),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_bio',
            field=models.CharField(blank=True, max_length=212),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.ProfileType'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='program_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.ProgramType'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='program_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.ProgramYear'),
        ),
    ]
