# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-01-30 01:08
from __future__ import unicode_literals

from django.db import migrations


def setup_default_values(apps, schema_editor):
    ProfileType = apps.get_model('profiles', 'ProfileType')
    ProfileType.objects.get_or_create(value='plain')
    ProfileType.objects.get_or_create(value='staff')
    ProfileType.objects.get_or_create(value='fellow')
    ProfileType.objects.get_or_create(value='board member')
    ProfileType.objects.get_or_create(value='grantee')

    ProgramType = apps.get_model('profiles', 'ProgramType')
    ProgramType.objects.get_or_create(value='tech policy fellowship')
    ProgramType.objects.get_or_create(value='mozfest speaker')

    ProgramYear = apps.get_model('profiles', 'ProgramYear')
    ProgramYear.objects.get_or_create(value='2015')
    ProgramYear.objects.get_or_create(value='2016')
    ProgramYear.objects.get_or_create(value='2017')
    ProgramYear.objects.get_or_create(value='2018')
    ProgramYear.objects.get_or_create(value='2019')


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_auto_20180130_0953'),
    ]

    operations = [
    	migrations.RunPython(setup_default_values),
    ]
