# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-02-13 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_auto_20180201_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='profile',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
