# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-15 21:17
from __future__ import unicode_literals

from django.db import migrations, models


def create_profiles_for_creators_without_profiles(apps, schema_editor):
    UserProfile = apps.get_model('profiles', 'UserProfile')
    Creator = apps.get_model('creators', 'Creator')
    for creator in Creator.objects.filter(profile__isnull=True):
        profile = UserProfile.objects.create(custom_name=creator.name)
        creator.profile = profile
        creator.save()


def create_entrycreators_for_orderedcreatorrecords(apps, schema_editor):
    OrderedCreatorRecord = apps.get_model('creators', 'OrderedCreatorRecord')
    EntryCreator = apps.get_model('creators', 'EntryCreator')
    for ocr in OrderedCreatorRecord.objects.all():
        EntryCreator.objects.create(
            entry=ocr.entry,
            profile=ocr.creator.profile
        )


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_auto_20180213_1202'),
        ('creators', '0013_auto_20180318_1808')
    ]

    operations = [
        # First increase the size of the name field in profiles to accommodate
        # creator's names which can be 140 characters long
        migrations.AlterField(
            model_name='userprofile',
            name='custom_name',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.RunPython(create_profiles_for_creators_without_profiles),
        migrations.RunPython(create_entrycreators_for_orderedcreatorrecords)
    ]
