# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-25 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_replace_creators_with_entrycreators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_bio_long',
            field=models.TextField(blank=True, max_length=4096),
        ),
    ]
