# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-14 19:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import pulseapi.profiles.models.organizations
import pulseapi.utility.model_fields


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
        ('profiles', '0019_auto_20180625_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Organization Name')),
                ('location', models.CharField(help_text='Full address of your headquarters including the city, region (if any), and country.', max_length=1024, verbose_name='Headquarters Location')),
                ('tagline', models.TextField(help_text='A short (max 140 characters) one-liner about your mission', max_length=140)),
                ('about', models.TextField(help_text='Describe what type of organization you are, the kind of work you do, what you offer, etc.', max_length=1024)),
                ('twitter', models.URLField(blank=True, help_text='Full url to Twitter profile', max_length=2048)),
                ('linkedin', models.URLField(blank=True, help_text='Full url to LinkedIn profile', max_length=2048)),
                ('email', models.EmailField(blank=True, help_text='A contact email for your organization', max_length=254, verbose_name='Organization Email')),
                ('website', models.URLField(blank=True, help_text="Full url to your organization's homepage", max_length=2048)),
                ('logo', models.ImageField(blank=True, max_length=2048, upload_to=pulseapi.profiles.models.organizations.org_profile_thumbnail_path)),
                ('temporary_code', pulseapi.utility.model_fields.TemporaryField()),
                ('administrator', models.ForeignKey(blank=True, help_text='Link an existing Pulse account to manage your organization’s profile', null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.UserProfile')),
                ('issues', models.ManyToManyField(blank=True, related_name='related_organizations', to='issues.Issue', verbose_name='Internet Health Issues')),
            ],
            options={
                'verbose_name': 'organization profile',
            },
        ),
    ]
