# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-05-08 17:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import pulseapi.utility.validators


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_auto_20180625_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_current', models.BooleanField(default=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_types', to='profiles.UserProfile')),
                ('profile_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_profiles', to='profiles.ProfileType')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramMembershipRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True, validators=[pulseapi.utility.validators.YearValidator(max_offset=2)])),
                ('cohort_name', models.CharField(blank=True, max_length=200, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_membership_records', to='profiles.UserProfile')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='membership_records', to='profiles.ProgramType')),
            ],
            options={
                'verbose_name': "record of a profile's membership in a program",
                'verbose_name_plural': 'records of program membership',
            },
        ),
        migrations.AlterOrderWithRespectTo(
            name='programmembershiprecord',
            order_with_respect_to='profile',
        ),
        migrations.AlterOrderWithRespectTo(
            name='profilerole',
            order_with_respect_to='profile',
        ),
    ]
