# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-05-07 22:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import pulseapi.utility.validators


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_auto_20180625_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileProfileType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_types', to='profiles.UserProfile')),
                ('profile_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_profiles', to='profiles.ProfileType')),
            ],
            options={
                'verbose_name': 'Role of a profile',
            },
        ),
        migrations.CreateModel(
            name='UserProfileProgramParticipation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True, validators=[pulseapi.utility.validators.YearValidator(max_offset=2)])),
                ('cohort', models.CharField(blank=True, max_length=200, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_participation', to='profiles.UserProfile')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participation', to='profiles.ProgramType')),
            ],
            options={
                'verbose_name': 'Profile participation in a program',
            },
        ),
        migrations.AlterOrderWithRespectTo(
            name='userprofileprogramparticipation',
            order_with_respect_to='profile',
        ),
        migrations.AlterOrderWithRespectTo(
            name='userprofileprofiletype',
            order_with_respect_to='profile',
        ),
    ]
