# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-05-07 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0020_auto_20190507_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileprofiletype',
            name='is_current',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='userprofileprofiletype',
            index=models.Index(fields=['profile', 'is_current', '_order'], name='uk_role_current_order'),
        ),
        migrations.AddIndex(
            model_name='userprofileprofiletype',
            index=models.Index(fields=['profile', 'is_current', 'profile_type'], name='uk_profileid_current_role'),
        ),
        migrations.AddIndex(
            model_name='userprofileprogramparticipation',
            index=models.Index(fields=['profile', '_order'], name='uk_participate_profileid_order'),
        ),
    ]
