# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-07 17:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0021_auto_20190508_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 26, 0, 0, tzinfo=utc)),
        ),
    ]
