# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-28 00:33
from __future__ import unicode_literals

from django.db import migrations, models
from django.utils.dateparse import parse_date
from django.utils.timezone import make_aware

def default_start_time():
    date_str = "2016-01-26"
    default_date = parse_date(date_str)
    return make_aware(default_date)

class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0021_auto_20190508_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=default_start_time),
            preserve_default=False,
        ),
    ]
