from django.conf.urls import url

from pulseapi.entries.views import (
    toggle_bookmark,
    toggle_moderation,
    toggle_featured,
    EntryView,
    BookmarkedEntries,
    ModerationStateView,
    EntriesListView,
    ProjectEntriesListView,
    NewsEntriesListView,
    CurriculumEntriesListView,
    InfoEntriesListView,
    SessionEntriesListView,
)

urlpatterns = [
    url(
        '^$',
        EntriesListView.as_view(),
        name='entries-list'
    ),
    url(
        'curriculum/',
        CurriculumEntriesListView.as_view(),
        name='curriculum-entries'
    ),
    url(
        'info/',
        InfoEntriesListView.as_view(),
        name='info-entries'
    ),
    url(
        'news/',
        NewsEntriesListView.as_view(),
        name='news-entries'
    ),
    url(
        'project/',
        ProjectEntriesListView.as_view(),
        name='project-entries'
    ),
    url(
        'session/',
        SessionEntriesListView.as_view(),
        name='session-entries'
    ),
    url(
        'bookmarks/',
        BookmarkedEntries.as_view(),
        name='user-bookmarks'
    ),
    url(
        r'^(?P<entryid>[0-9]+)/bookmark/?',
        toggle_bookmark,
        name='bookmark'
    ),
    url(
        r'^(?P<entryid>[0-9]+)/moderate/(?P<stateid>[0-9]+)/?',
        toggle_moderation,
        name='moderate'
    ),
    url(
        r'^(?P<entryid>[0-9]+)/feature/?',
        toggle_featured,
        name='feature'
    ),
    url(
        r'^(?P<pk>[0-9]+)/',
        EntryView.as_view(),
        name='entry'
    ),
    url(
        'moderation-states/',
        ModerationStateView.as_view(),
        name='moderation-states'
    )
]
