# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('content_url', models.URLField()),
                ('thumbnail_url', models.URLField()),
                ('get_involved', models.CharField(max_length=300)),
                ('get_involved_url', models.URLField()),
                ('interest', models.CharField(max_length=300)),
                ('featured', models.BooleanField()),
                ('issues', models.ManyToManyField(blank=True, related_name='entries', to='issues.Issue')),
                ('tags', models.ManyToManyField(blank=True, related_name='entries', to='tags.Tag')),
            ],
            options={
                'verbose_name_plural': 'entries',
            },
        ),
    ]
