# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 21:13
from __future__ import unicode_literals

from django.db import migrations, models

def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Issue = apps.get_model("issues", "Issue")
    db_alias = schema_editor.connection.alias
    Issue.objects.using(db_alias).bulk_create([
        Issue(name="Decentralization", description="A description of decentralization"),
        Issue(name="Open Innovation", description="A description of open innovation"),
    ])

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.RunPython(forwards_func),
    ]
