# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-14 20:27
from __future__ import unicode_literals

from django.db import migrations, models
from django.contrib.auth.models import Group, Permission
from pulseapi.users.models import EmailUser

def forwards_func(apps, schema_editor):
    # anyone who had staff permissions was a full
    # admin, so carry those rights over. Also make
    # sure that anyone who had staff permissions
    # gets be added to the staff group.
    users = EmailUser.objects.all()
    staff_group = Group.objects.get_or_create(name='staff')
    for user in users:
        if user.is_staff is True:
            staff_group.add(user)
            user.is_superuser = True
            user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='emailuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.RunPython(forwards_func),
    ]
