# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-14 19:08
from __future__ import unicode_literals

from django.db import migrations, models
from pulseapi.users.models import EmailUser

def forwards_func(apps, schema_editor):
    # anyone who had staff permissions was an full
    # admin, so carry those rights over.
    users = EmailUser.objects.all()
    for user in users:
        if user.is_staff is True:
            user.is_superuser = True
            user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(forwards_func),
    ]
