# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-16 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170616_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailuser',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='this user counts as django::staff'),
        ),
    ]
