# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-04 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170616_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbookmarks',
            name='entry',
        ),
        migrations.RemoveField(
            model_name='userbookmarks',
            name='user',
        ),
        migrations.AlterField(
            model_name='emailuser',
            name='bookmarks',
            field=models.ManyToManyField(related_name='bookmark_by_profile', through='profiles.UserBookmarks', to='entries.Entry'),
        ),
        migrations.DeleteModel(
            name='UserBookmarks',
        ),
    ]
