# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-04 20:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rebind_userbookmarks_from_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailuser',
            name='bookmarks',
        ),
    ]
