# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-29 18:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_auto_20170929_1810'),
        ('users', '0006_remove_emailuser_bookmarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailuser',
            name='profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_user', to='profiles.UserProfile'),
        ),
    ]
