# Generated by Django 2.2.13 on 2022-04-11 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20180823_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is this user active (i.e. can they log in)'),
        ),
    ]
